//constants for the
export const userConstants = {
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",
  LOADING_USER: "LOADING_USER",

  FINGERPRINT_ADDED: "FINGERPRINT_ADDED",
  FINGERPRINT_UPDATED: "FINGERPRINT_UPDATED",
  GET_BRANCHES_SUCCESS: "GET_BRANCHES_SUCCESS",
  GET_BRANCHES_FAIL: "GET_BRANCHES_FAIL",
  ACCOUNT_EDIT_SUCCESS: "ACCOUNT_EDIT_SUCCESS",
  VERIFY_CHEQUE_REQUEST_SUCCESS: "VERIFY_CHEQUE_REQUEST_SUCCESS",
  VERIFY_CHEQUE_REQUEST_FAIL: "VERIFY_CHEQUE_REQUEST_FAIL",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAIL: "GET_USERS_FAIL",
  CLEAR_IMAGE_GALLERY:"CLEAR_IMAGE_GALLERY"
};
